/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/v1/ai-jobs/{job_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Ai Job */
        get: operations["get_ai_job_api_v1_ai_jobs__job_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/ai-settings": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Ai Settings */
        get: operations["get_ai_settings_api_v1_ai_settings_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/login": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Login */
        post: operations["login_api_v1_auth_login_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/logout": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Logout */
        post: operations["logout_api_v1_auth_logout_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/me": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Me */
        get: operations["me_api_v1_auth_me_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/dashboard": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Dashboard */
        get: operations["dashboard_api_v1_dashboard_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/lesson-documents/{document_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        /** Save Lesson Document */
        put: operations["save_lesson_document_api_v1_lesson_documents__document_id__put"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/lesson-documents/{document_id}/approve": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Approve Document */
        post: operations["approve_document_api_v1_lesson_documents__document_id__approve_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/lesson-documents/{document_id}/export.docx": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Export Document Docx */
        post: operations["export_document_docx_api_v1_lesson_documents__document_id__export_docx_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/lesson-documents/{document_id}/regenerate-section": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Regenerate Document Section */
        post: operations["regenerate_document_section_api_v1_lesson_documents__document_id__regenerate_section_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/lesson-documents/{document_id}/reject": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Reject Document */
        post: operations["reject_document_api_v1_lesson_documents__document_id__reject_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/lesson-documents/{document_id}/submit": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Submit Document */
        post: operations["submit_document_api_v1_lesson_documents__document_id__submit_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/lesson-documents/{document_id}/versions": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Document Versions */
        get: operations["list_document_versions_api_v1_lesson_documents__document_id__versions_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/lessons": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Lessons */
        get: operations["list_lessons_api_v1_lessons_get"];
        put?: never;
        /** Create Lesson */
        post: operations["create_lesson_api_v1_lessons_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/lessons/{lesson_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Lesson */
        get: operations["get_lesson_api_v1_lessons__lesson_id__get"];
        /** Update Lesson */
        put: operations["update_lesson_api_v1_lessons__lesson_id__put"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/lessons/{lesson_id}/cancel": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Cancel Lesson */
        post: operations["cancel_lesson_api_v1_lessons__lesson_id__cancel_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/lessons/{lesson_id}/complete": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Complete Lesson */
        post: operations["complete_lesson_api_v1_lessons__lesson_id__complete_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/lessons/{lesson_id}/document": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Lesson Document */
        get: operations["get_lesson_document_api_v1_lessons__lesson_id__document_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/lessons/{lesson_id}/documents/generate": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Generate Lesson Document */
        post: operations["generate_lesson_document_api_v1_lessons__lesson_id__documents_generate_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/lessons/{lesson_id}/reschedule": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Reschedule Lesson */
        post: operations["reschedule_lesson_api_v1_lessons__lesson_id__reschedule_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/prompt-templates": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Prompt Templates */
        get: operations["list_prompt_templates_api_v1_prompt_templates_get"];
        put?: never;
        /** Create Prompt Template */
        post: operations["create_prompt_template_api_v1_prompt_templates_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/prompt-templates/{template_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        /** Update Prompt Template */
        put: operations["update_prompt_template_api_v1_prompt_templates__template_id__put"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/student-subjects": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Student Subjects */
        get: operations["list_student_subjects_api_v1_student_subjects_get"];
        put?: never;
        /** Create Student Subject */
        post: operations["create_student_subject_api_v1_student_subjects_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/student-subjects/{entity_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        /** Update Student Subject */
        put: operations["update_student_subject_api_v1_student_subjects__entity_id__put"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/student-subjects/{entity_id}/archive": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Archive Student Subject */
        post: operations["archive_student_subject_api_v1_student_subjects__entity_id__archive_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/students": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Students */
        get: operations["list_students_api_v1_students_get"];
        put?: never;
        /** Create Student */
        post: operations["create_student_api_v1_students_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/students/{student_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Student */
        get: operations["get_student_api_v1_students__student_id__get"];
        /** Update Student */
        put: operations["update_student_api_v1_students__student_id__put"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/students/{student_id}/archive": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Archive Student */
        post: operations["archive_student_api_v1_students__student_id__archive_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/subjects": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Subjects */
        get: operations["list_subjects_api_v1_subjects_get"];
        put?: never;
        /** Create Subject */
        post: operations["create_subject_api_v1_subjects_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/subjects/{subject_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        /** Update Subject */
        put: operations["update_subject_api_v1_subjects__subject_id__put"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/subjects/{subject_id}/archive": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Archive Subject */
        post: operations["archive_subject_api_v1_subjects__subject_id__archive_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/teaching-plan-items/{item_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        /** Update Plan Item */
        put: operations["update_plan_item_api_v1_teaching_plan_items__item_id__put"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/teaching-plans": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Plans */
        get: operations["list_plans_api_v1_teaching_plans_get"];
        put?: never;
        /** Create Plan */
        post: operations["create_plan_api_v1_teaching_plans_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/teaching-plans/{plan_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Plan */
        get: operations["get_plan_api_v1_teaching_plans__plan_id__get"];
        /** Update Plan Record */
        put: operations["update_plan_record_api_v1_teaching_plans__plan_id__put"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/teaching-plans/{plan_id}/archive": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Archive Plan */
        post: operations["archive_plan_api_v1_teaching_plans__plan_id__archive_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/teaching-plans/{plan_id}/items": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Create Plan Item */
        post: operations["create_plan_item_api_v1_teaching_plans__plan_id__items_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/teaching-plans/{plan_id}/revisions": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Plan Revisions */
        get: operations["list_plan_revisions_api_v1_teaching_plans__plan_id__revisions_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/health/live": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Live */
        get: operations["live_health_live_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/health/ready": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Ready */
        get: operations["ready_health_ready_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** AIJobResponse */
        AIJobResponse: {
            /** Attempts Count */
            attempts_count: number;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /** Error Code */
            error_code: string | null;
            /** Error Message */
            error_message: string | null;
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Max Attempts */
            max_attempts: number;
            /** Model */
            model: string | null;
            /** Provider */
            provider: string;
            status: components["schemas"]["AIJobStatus"];
            /** Task Type */
            task_type: string;
            /**
             * Updated At
             * Format: date-time
             */
            updated_at: string;
        };
        /**
         * AIJobStatus
         * @enum {string}
         */
        AIJobStatus: "QUEUED" | "RUNNING" | "SUCCEEDED" | "FAILED" | "CANCELED";
        /** AISettingsResponse */
        AISettingsResponse: {
            /**
             * Development Default Is Mock
             * @default true
             */
            development_default_is_mock: boolean;
            /** Model */
            model: string | null;
            /** Provider */
            provider: string;
            /** Real Provider Configured */
            real_provider_configured: boolean;
        };
        /** ArchiveRequest */
        ArchiveRequest: {
            /** Reason */
            reason: string;
            /** Version */
            version: number;
        };
        /** AuthUser */
        AuthUser: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Username */
            username: string;
        };
        /** DashboardProgress */
        DashboardProgress: {
            /** Completed Items */
            completed_items: number;
            /** Percent */
            percent: number;
            /** Student Name */
            student_name: string;
            /**
             * Student Subject Id
             * Format: uuid
             */
            student_subject_id: string;
            /** Subject Name */
            subject_name: string;
            /** Total Items */
            total_items: number;
        };
        /** DashboardResponse */
        DashboardResponse: {
            /** Completed This Month */
            completed_this_month: number;
            /** Next Seven Days */
            next_seven_days: components["schemas"]["LessonResponse"][];
            /** Planned This Week */
            planned_this_week: number;
            /** Progress */
            progress: components["schemas"]["DashboardProgress"][];
            /**
             * Timezone
             * @default Asia/Shanghai
             * @constant
             */
            timezone: "Asia/Shanghai";
            /** Today */
            today: components["schemas"]["LessonResponse"][];
        };
        /** DocumentVersionResponse */
        DocumentVersionResponse: {
            /** Ai Job Id */
            ai_job_id: string | null;
            /** Change Summary */
            change_summary: string;
            content: components["schemas"]["LessonPlanContent"];
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /** Docx Object Key */
            docx_object_key: string | null;
            /**
             * Id
             * Format: uuid
             */
            id: string;
            source: components["schemas"]["DocumentVersionSource"];
            status: components["schemas"]["ReviewStatus"];
            /** Version Number */
            version_number: number;
        };
        /**
         * DocumentVersionSource
         * @enum {string}
         */
        DocumentVersionSource: "AI_GENERATED" | "MANUAL_EDIT" | "PARTIAL_REGENERATION";
        /** GenerateLessonPlanRequest */
        GenerateLessonPlanRequest: {
            /** Extra Requirements */
            extra_requirements?: string | null;
            /** Template Id */
            template_id?: string | null;
        };
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /** HealthResponse */
        HealthResponse: {
            /** Database */
            database?: "ok" | null;
            /** Migration */
            migration?: string | null;
            /** Service */
            service: string;
            /**
             * Status
             * @default ok
             * @constant
             */
            status: "ok";
        };
        /** LessonCancel */
        LessonCancel: {
            /** Reason */
            reason: string;
            /** Version */
            version: number;
        };
        /** LessonComplete */
        LessonComplete: {
            /** Actual Minutes */
            actual_minutes: number;
            /**
             * Adjustment Reason
             * @default 课程完成时确认教学进度
             */
            adjustment_reason: string;
            /** Progress Updates */
            progress_updates?: components["schemas"]["ProgressConfirmation"][];
        };
        /** LessonCreate */
        LessonCreate: {
            lesson_type: components["schemas"]["LessonType"];
            /** Makeup For Lesson Id */
            makeup_for_lesson_id?: string | null;
            /** Plan Item Ids */
            plan_item_ids?: string[];
            /** Planned Minutes */
            planned_minutes: number;
            /**
             * Scheduled Start
             * Format: date-time
             */
            scheduled_start: string;
            /** Special Requirements */
            special_requirements?: string | null;
            /**
             * Student Subject Id
             * Format: uuid
             */
            student_subject_id: string;
            /** Theme */
            theme: string;
        };
        /** LessonDocumentResponse */
        LessonDocumentResponse: {
            /** Approved Version Number */
            approved_version_number: number | null;
            current_version: components["schemas"]["DocumentVersionResponse"];
            /** Current Version Number */
            current_version_number: number;
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /**
             * Lesson Id
             * Format: uuid
             */
            lesson_id: string;
            status: components["schemas"]["ReviewStatus"];
            /** Title */
            title: string;
            /** Version */
            version: number;
        };
        /** LessonPlanContent */
        LessonPlanContent: {
            /** Common Mistakes */
            common_mistakes: string[];
            /** Examples */
            examples: components["schemas"]["QuestionItem"][];
            /** Homework */
            homework: components["schemas"]["QuestionItem"][];
            /** In Class Exercises */
            in_class_exercises: components["schemas"]["QuestionItem"][];
            /** Knowledge Explanations */
            knowledge_explanations: components["schemas"]["TeachingSection"][];
            /** Objectives */
            objectives: string[];
            /** Schedule */
            schedule: components["schemas"]["TimeBlock"][];
            /**
             * Schema Version
             * @constant
             */
            schema_version: "1.0";
            /** Teacher Notes */
            teacher_notes: string[];
        };
        /** LessonReschedule */
        LessonReschedule: {
            /** Planned Minutes */
            planned_minutes?: number | null;
            /** Reason */
            reason: string;
            /**
             * Scheduled Start
             * Format: date-time
             */
            scheduled_start: string;
            /** Version */
            version: number;
        };
        /** LessonResponse */
        LessonResponse: {
            /** Actual Minutes */
            actual_minutes: number | null;
            /** Cancellation Reason */
            cancellation_reason: string | null;
            /**
             * Id
             * Format: uuid
             */
            id: string;
            lesson_type: components["schemas"]["LessonType"];
            /** Makeup For Lesson Id */
            makeup_for_lesson_id: string | null;
            /** Plan Item Ids */
            plan_item_ids: string[];
            /** Planned Minutes */
            planned_minutes: number;
            /** Rescheduled From Lesson Id */
            rescheduled_from_lesson_id: string | null;
            /**
             * Scheduled Start
             * Format: date-time
             */
            scheduled_start: string;
            /** Special Requirements */
            special_requirements: string | null;
            status: components["schemas"]["LessonStatus"];
            /** Student Name */
            student_name: string;
            /**
             * Student Subject Id
             * Format: uuid
             */
            student_subject_id: string;
            /** Subject Name */
            subject_name: string;
            /** Theme */
            theme: string;
            /** Version */
            version: number;
        };
        /**
         * LessonStatus
         * @enum {string}
         */
        LessonStatus: "PLANNED" | "COMPLETED" | "CANCELED" | "RESCHEDULED";
        /**
         * LessonType
         * @enum {string}
         */
        LessonType: "NEW_LESSON" | "REVIEW" | "EXERCISE" | "EXAM" | "PAPER_REVIEW";
        /** LessonUpdate */
        LessonUpdate: {
            lesson_type: components["schemas"]["LessonType"];
            /** Plan Item Ids */
            plan_item_ids?: string[];
            /** Planned Minutes */
            planned_minutes: number;
            /**
             * Scheduled Start
             * Format: date-time
             */
            scheduled_start: string;
            /** Special Requirements */
            special_requirements?: string | null;
            /** Theme */
            theme: string;
            /** Version */
            version: number;
        };
        /** LoginRequest */
        LoginRequest: {
            /** Password */
            password: string;
            /** Username */
            username: string;
        };
        /** LoginResponse */
        LoginResponse: {
            user: components["schemas"]["AuthUser"];
        };
        /** PlanCreate */
        PlanCreate: {
            /** Description */
            description?: string | null;
            /** Name */
            name: string;
            /**
             * Student Subject Id
             * Format: uuid
             */
            student_subject_id: string;
        };
        /** PlanItemCreate */
        PlanItemCreate: {
            /** Adjustment Reason */
            adjustment_reason: string;
            /** Description */
            description?: string | null;
            /**
             * Estimated Minutes
             * @default 0
             */
            estimated_minutes: number;
            item_type: components["schemas"]["PlanItemType"];
            /** Parent Id */
            parent_id?: string | null;
            /**
             * Sort Order
             * @default 0
             */
            sort_order: number;
            /** Title */
            title: string;
        };
        /** PlanItemResponse */
        PlanItemResponse: {
            /** Actual Minutes */
            actual_minutes: number;
            /** Description */
            description: string | null;
            /** Estimated Minutes */
            estimated_minutes: number;
            /**
             * Id
             * Format: uuid
             */
            id: string;
            item_type: components["schemas"]["PlanItemType"];
            /** Parent Id */
            parent_id: string | null;
            /**
             * Plan Id
             * Format: uuid
             */
            plan_id: string;
            /** Progress Notes */
            progress_notes: string | null;
            /** Sort Order */
            sort_order: number;
            status: components["schemas"]["PlanItemStatus"];
            /** Title */
            title: string;
            /** Version */
            version: number;
        };
        /**
         * PlanItemStatus
         * @enum {string}
         */
        PlanItemStatus: "NOT_STARTED" | "IN_PROGRESS" | "COMPLETED" | "REVIEW_NEEDED";
        /**
         * PlanItemType
         * @enum {string}
         */
        PlanItemType: "CHAPTER" | "KNOWLEDGE_POINT" | "TOPIC";
        /** PlanItemUpdate */
        PlanItemUpdate: {
            /**
             * Actual Minutes
             * @default 0
             */
            actual_minutes: number;
            /** Adjustment Reason */
            adjustment_reason: string;
            /** Description */
            description?: string | null;
            /**
             * Estimated Minutes
             * @default 0
             */
            estimated_minutes: number;
            item_type: components["schemas"]["PlanItemType"];
            /** Parent Id */
            parent_id?: string | null;
            /** Progress Notes */
            progress_notes?: string | null;
            /**
             * Sort Order
             * @default 0
             */
            sort_order: number;
            status: components["schemas"]["PlanItemStatus"];
            /** Title */
            title: string;
            /** Version */
            version: number;
        };
        /** PlanResponse */
        PlanResponse: {
            /** Archived At */
            archived_at: string | null;
            /** Description */
            description: string | null;
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Items */
            items?: components["schemas"]["PlanItemResponse"][];
            /** Name */
            name: string;
            /** Student Name */
            student_name: string;
            /**
             * Student Subject Id
             * Format: uuid
             */
            student_subject_id: string;
            /** Subject Name */
            subject_name: string;
            /** Version */
            version: number;
        };
        /** PlanRevisionResponse */
        PlanRevisionResponse: {
            /** Adjustment Reason */
            adjustment_reason: string;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /** Version Number */
            version_number: number;
        };
        /** PlanUpdate */
        PlanUpdate: {
            /** Adjustment Reason */
            adjustment_reason: string;
            /** Description */
            description?: string | null;
            /** Name */
            name: string;
            /** Version */
            version: number;
        };
        /** ProgressConfirmation */
        ProgressConfirmation: {
            /**
             * Actual Minutes Delta
             * @default 0
             */
            actual_minutes_delta: number;
            /**
             * Plan Item Id
             * Format: uuid
             */
            plan_item_id: string;
            /** Progress Notes */
            progress_notes?: string | null;
            status: components["schemas"]["PlanItemStatus"];
        };
        /** PromptTemplateCreate */
        PromptTemplateCreate: {
            /** Change Reason */
            change_reason: string;
            /** Grade Band */
            grade_band?: string | null;
            /** Name */
            name: string;
            /** Purpose */
            purpose: string;
            /** Subject Id */
            subject_id?: string | null;
            /** System Prompt */
            system_prompt: string;
            /** Template Key */
            template_key: string;
            /** User Prompt Template */
            user_prompt_template: string;
        };
        /** PromptTemplateResponse */
        PromptTemplateResponse: {
            current_version: components["schemas"]["PromptTemplateVersionResponse"];
            /** Current Version Number */
            current_version_number: number;
            /** Grade Band */
            grade_band: string | null;
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Name */
            name: string;
            /** Purpose */
            purpose: string;
            /** Subject Id */
            subject_id: string | null;
            /** Template Key */
            template_key: string;
        };
        /** PromptTemplateUpdate */
        PromptTemplateUpdate: {
            /** Change Reason */
            change_reason: string;
            /** Current Version Number */
            current_version_number: number;
            /** Name */
            name: string;
            /** System Prompt */
            system_prompt: string;
            /** User Prompt Template */
            user_prompt_template: string;
        };
        /** PromptTemplateVersionResponse */
        PromptTemplateVersionResponse: {
            /** Change Reason */
            change_reason: string;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Output Schema */
            output_schema: {
                [key: string]: unknown;
            };
            /** System Prompt */
            system_prompt: string;
            /** User Prompt Template */
            user_prompt_template: string;
            /** Version Number */
            version_number: number;
        };
        /** QuestionItem */
        QuestionItem: {
            /** Analysis Markdown */
            analysis_markdown: string;
            /** Answer Markdown */
            answer_markdown: string;
            /**
             * Difficulty
             * @enum {string}
             */
            difficulty: "BASIC" | "MEDIUM" | "CHALLENGING";
            /** Id */
            id: string;
            /** Stem Markdown */
            stem_markdown: string;
        };
        /** RegenerateSectionRequest */
        RegenerateSectionRequest: {
            /** Instructions */
            instructions: string;
            /**
             * Section
             * @enum {string}
             */
            section: "objectives" | "schedule" | "knowledge_explanations" | "examples" | "in_class_exercises" | "common_mistakes" | "homework" | "teacher_notes";
            /** Version */
            version: number;
        };
        /** ReviewActionRequest */
        ReviewActionRequest: {
            /** Reason */
            reason: string;
            /** Version */
            version: number;
        };
        /**
         * ReviewStatus
         * @enum {string}
         */
        ReviewStatus: "DRAFT" | "PENDING_REVIEW" | "APPROVED" | "REJECTED" | "SUPERSEDED";
        /** SaveDocumentRequest */
        SaveDocumentRequest: {
            /** Change Summary */
            change_summary: string;
            content: components["schemas"]["LessonPlanContent"];
            /** Version */
            version: number;
        };
        /** StudentCreate */
        StudentCreate: {
            /** Display Name */
            display_name: string;
            /** Grade */
            grade?: string | null;
            /** Guardian Requirements */
            guardian_requirements?: string | null;
            /** Learning Characteristics */
            learning_characteristics?: string | null;
            /** Notes */
            notes?: string | null;
            /** Region */
            region?: string | null;
            /** School */
            school?: string | null;
        };
        /** StudentResponse */
        StudentResponse: {
            /** Archived At */
            archived_at: string | null;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /** Display Name */
            display_name: string;
            /** Grade */
            grade?: string | null;
            /** Guardian Requirements */
            guardian_requirements?: string | null;
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Learning Characteristics */
            learning_characteristics?: string | null;
            /** Notes */
            notes?: string | null;
            /** Region */
            region?: string | null;
            /** School */
            school?: string | null;
            /**
             * Updated At
             * Format: date-time
             */
            updated_at: string;
            /** Version */
            version: number;
        };
        /** StudentSubjectCreate */
        StudentSubjectCreate: {
            /** Attention Notes */
            attention_notes?: string | null;
            /** Current Foundation */
            current_foundation?: string | null;
            /** Overall Goal */
            overall_goal?: string | null;
            /** Stage Goal */
            stage_goal?: string | null;
            /**
             * Student Id
             * Format: uuid
             */
            student_id: string;
            /**
             * Subject Id
             * Format: uuid
             */
            subject_id: string;
            /** Teaching Requirements */
            teaching_requirements?: string | null;
            /** Textbook Version */
            textbook_version?: string | null;
        };
        /** StudentSubjectResponse */
        StudentSubjectResponse: {
            /** Archived At */
            archived_at: string | null;
            /** Attention Notes */
            attention_notes?: string | null;
            /** Current Foundation */
            current_foundation?: string | null;
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Overall Goal */
            overall_goal?: string | null;
            /** Stage Goal */
            stage_goal?: string | null;
            /**
             * Student Id
             * Format: uuid
             */
            student_id: string;
            /** Student Name */
            student_name: string;
            /**
             * Subject Id
             * Format: uuid
             */
            subject_id: string;
            /** Subject Name */
            subject_name: string;
            /** Teaching Requirements */
            teaching_requirements?: string | null;
            /** Textbook Version */
            textbook_version?: string | null;
            /** Version */
            version: number;
        };
        /** StudentSubjectUpdate */
        StudentSubjectUpdate: {
            /** Attention Notes */
            attention_notes?: string | null;
            /** Current Foundation */
            current_foundation?: string | null;
            /** Overall Goal */
            overall_goal?: string | null;
            /** Stage Goal */
            stage_goal?: string | null;
            /** Teaching Requirements */
            teaching_requirements?: string | null;
            /** Textbook Version */
            textbook_version?: string | null;
            /** Version */
            version: number;
        };
        /** StudentUpdate */
        StudentUpdate: {
            /** Display Name */
            display_name: string;
            /** Grade */
            grade?: string | null;
            /** Guardian Requirements */
            guardian_requirements?: string | null;
            /** Learning Characteristics */
            learning_characteristics?: string | null;
            /** Notes */
            notes?: string | null;
            /** Region */
            region?: string | null;
            /** School */
            school?: string | null;
            /** Version */
            version: number;
        };
        /** SubjectCreate */
        SubjectCreate: {
            /** Description */
            description?: string | null;
            /** Name */
            name: string;
        };
        /** SubjectResponse */
        SubjectResponse: {
            /** Archived At */
            archived_at: string | null;
            /** Description */
            description?: string | null;
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Name */
            name: string;
            /** Version */
            version: number;
        };
        /** SubjectUpdate */
        SubjectUpdate: {
            /** Description */
            description?: string | null;
            /** Name */
            name: string;
            /** Version */
            version: number;
        };
        /** TeachingSection */
        TeachingSection: {
            /** Body Markdown */
            body_markdown: string;
            /** Id */
            id: string;
            /** Title */
            title: string;
        };
        /** TimeBlock */
        TimeBlock: {
            /** Activities Markdown */
            activities_markdown: string;
            /** Minutes */
            minutes: number;
            /** Title */
            title: string;
        };
        /** ValidationError */
        ValidationError: {
            /** Context */
            ctx?: Record<string, never>;
            /** Input */
            input?: unknown;
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    get_ai_job_api_v1_ai_jobs__job_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                job_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AIJobResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_ai_settings_api_v1_ai_settings_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AISettingsResponse"];
                };
            };
        };
    };
    login_api_v1_auth_login_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["LoginRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["LoginResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    logout_api_v1_auth_logout_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    me_api_v1_auth_me_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AuthUser"];
                };
            };
        };
    };
    dashboard_api_v1_dashboard_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DashboardResponse"];
                };
            };
        };
    };
    save_lesson_document_api_v1_lesson_documents__document_id__put: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                document_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SaveDocumentRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["LessonDocumentResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    approve_document_api_v1_lesson_documents__document_id__approve_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                document_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ReviewActionRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["LessonDocumentResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    export_document_docx_api_v1_lesson_documents__document_id__export_docx_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                document_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    regenerate_document_section_api_v1_lesson_documents__document_id__regenerate_section_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                document_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RegenerateSectionRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            202: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AIJobResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    reject_document_api_v1_lesson_documents__document_id__reject_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                document_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ReviewActionRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["LessonDocumentResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    submit_document_api_v1_lesson_documents__document_id__submit_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                document_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ReviewActionRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["LessonDocumentResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_document_versions_api_v1_lesson_documents__document_id__versions_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                document_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DocumentVersionResponse"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_lessons_api_v1_lessons_get: {
        parameters: {
            query?: {
                start?: string | null;
                end?: string | null;
                student_subject_id?: string | null;
                status?: components["schemas"]["LessonStatus"] | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["LessonResponse"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    create_lesson_api_v1_lessons_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["LessonCreate"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["LessonResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_lesson_api_v1_lessons__lesson_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                lesson_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["LessonResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    update_lesson_api_v1_lessons__lesson_id__put: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                lesson_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["LessonUpdate"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["LessonResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    cancel_lesson_api_v1_lessons__lesson_id__cancel_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                lesson_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["LessonCancel"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["LessonResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    complete_lesson_api_v1_lessons__lesson_id__complete_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                lesson_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["LessonComplete"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["LessonResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_lesson_document_api_v1_lessons__lesson_id__document_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                lesson_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["LessonDocumentResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    generate_lesson_document_api_v1_lessons__lesson_id__documents_generate_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                lesson_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["GenerateLessonPlanRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            202: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AIJobResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    reschedule_lesson_api_v1_lessons__lesson_id__reschedule_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                lesson_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["LessonReschedule"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["LessonResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_prompt_templates_api_v1_prompt_templates_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PromptTemplateResponse"][];
                };
            };
        };
    };
    create_prompt_template_api_v1_prompt_templates_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["PromptTemplateCreate"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PromptTemplateResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    update_prompt_template_api_v1_prompt_templates__template_id__put: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                template_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["PromptTemplateUpdate"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PromptTemplateResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_student_subjects_api_v1_student_subjects_get: {
        parameters: {
            query?: {
                student_id?: string | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["StudentSubjectResponse"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    create_student_subject_api_v1_student_subjects_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["StudentSubjectCreate"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["StudentSubjectResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    update_student_subject_api_v1_student_subjects__entity_id__put: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                entity_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["StudentSubjectUpdate"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["StudentSubjectResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    archive_student_subject_api_v1_student_subjects__entity_id__archive_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                entity_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ArchiveRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["StudentSubjectResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_students_api_v1_students_get: {
        parameters: {
            query?: {
                include_archived?: boolean;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["StudentResponse"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    create_student_api_v1_students_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["StudentCreate"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["StudentResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_student_api_v1_students__student_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                student_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["StudentResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    update_student_api_v1_students__student_id__put: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                student_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["StudentUpdate"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["StudentResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    archive_student_api_v1_students__student_id__archive_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                student_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ArchiveRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["StudentResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_subjects_api_v1_subjects_get: {
        parameters: {
            query?: {
                include_archived?: boolean;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SubjectResponse"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    create_subject_api_v1_subjects_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SubjectCreate"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SubjectResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    update_subject_api_v1_subjects__subject_id__put: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                subject_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SubjectUpdate"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SubjectResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    archive_subject_api_v1_subjects__subject_id__archive_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                subject_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ArchiveRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SubjectResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    update_plan_item_api_v1_teaching_plan_items__item_id__put: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                item_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["PlanItemUpdate"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PlanItemResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_plans_api_v1_teaching_plans_get: {
        parameters: {
            query?: {
                student_subject_id?: string | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PlanResponse"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    create_plan_api_v1_teaching_plans_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["PlanCreate"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PlanResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_plan_api_v1_teaching_plans__plan_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                plan_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PlanResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    update_plan_record_api_v1_teaching_plans__plan_id__put: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                plan_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["PlanUpdate"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PlanResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    archive_plan_api_v1_teaching_plans__plan_id__archive_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                plan_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ArchiveRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PlanResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    create_plan_item_api_v1_teaching_plans__plan_id__items_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                plan_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["PlanItemCreate"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PlanItemResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_plan_revisions_api_v1_teaching_plans__plan_id__revisions_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                plan_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PlanRevisionResponse"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    live_health_live_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HealthResponse"];
                };
            };
        };
    };
    ready_health_ready_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HealthResponse"];
                };
            };
        };
    };
}
