import type { components } from "@teacher-workspace/api-client";

export type AuthUser = components["schemas"]["AuthUser"];
export type Student = components["schemas"]["StudentResponse"];
export type Subject = components["schemas"]["SubjectResponse"];
export type StudentSubject = components["schemas"]["StudentSubjectResponse"];
export type Plan = components["schemas"]["PlanResponse"];
export type PlanItem = components["schemas"]["PlanItemResponse"];
export type PlanRevision = components["schemas"]["PlanRevisionResponse"];
export type Lesson = components["schemas"]["LessonResponse"];
export type Dashboard = components["schemas"]["DashboardResponse"];
export type LessonType = components["schemas"]["LessonType"];
export type PlanItemStatus = components["schemas"]["PlanItemStatus"];
export type PlanItemType = components["schemas"]["PlanItemType"];
export type LessonDocument = components["schemas"]["LessonDocumentResponse"];
export type LessonPlanContent = components["schemas"]["LessonPlanContent"];
export type DocumentVersion = components["schemas"]["DocumentVersionResponse"];
export type AIJob = components["schemas"]["AIJobResponse"];
export type PromptTemplate = components["schemas"]["PromptTemplateResponse"];
export type AISettings = components["schemas"]["AISettingsResponse"];
export type AIUsage = components["schemas"]["AIUsageResponse"];
export type Material = components["schemas"]["MaterialResponse"];
export type LessonFeedback = components["schemas"]["LessonFeedbackResponse"];
export type LessonFeedbackContent = components["schemas"]["LessonFeedbackContent"];
export type FeedbackVersion = components["schemas"]["FeedbackVersionResponse"];
export type Mastery = components["schemas"]["MasteryResponse"];
