"use client";

import { useQuery, useQueryClient } from "@tanstack/react-query";
import { FormEvent, useState } from "react";

import { EmptyState, ErrorNotice, PageHeader } from "@/components/page-ui";
import { api, jsonBody } from "@/lib/api";
import type { Plan, PlanItem, PlanItemStatus, PlanRevision, StudentSubject } from "@/lib/types";

const statusLabels: Record<PlanItemStatus, string> = { NOT_STARTED: "未开始", IN_PROGRESS: "进行中", COMPLETED: "已完成", REVIEW_NEEDED: "需要复习" };

export default function PlansPage() {
  const client = useQueryClient();
  const links = useQuery({ queryKey: ["student-subjects"], queryFn: () => api<StudentSubject[]>("/student-subjects") });
  const plans = useQuery({ queryKey: ["plans"], queryFn: () => api<Plan[]>("/teaching-plans") });
  const [selectedId, setSelectedId] = useState<string>();
  const selected = plans.data?.find((row) => row.id === selectedId) ?? plans.data?.[0];
  const selectedItems = selected?.items ?? [];
  const revisions = useQuery({ queryKey: ["plan-revisions", selected?.id], queryFn: () => api<PlanRevision[]>(`/teaching-plans/${selected!.id}/revisions`), enabled: Boolean(selected) });
  const [newPlan, setNewPlan] = useState({ student_subject_id: "", name: "", description: "" });
  const [newItem, setNewItem] = useState({ title: "", item_type: "KNOWLEDGE_POINT", parent_id: "", estimated_minutes: "120", sort_order: "0" });
  const [error, setError] = useState<unknown>();
  async function refresh() { await Promise.all([client.invalidateQueries({ queryKey: ["plans"] }), client.invalidateQueries({ queryKey: ["dashboard"] })]); }
  async function createPlan(event: FormEvent) { event.preventDefault(); try { const row = await api<Plan>("/teaching-plans", { method: "POST", ...jsonBody({ ...newPlan, description: newPlan.description || null }) }); setNewPlan({ student_subject_id: "", name: "", description: "" }); setSelectedId(row.id); await refresh(); } catch (caught) { setError(caught); } }
  async function createItem(event: FormEvent) { event.preventDefault(); if (!selected) return; const reason = window.prompt("请输入本次计划调整原因", "新增计划条目"); if (!reason) return; try { await api(`/teaching-plans/${selected.id}/items`, { method: "POST", ...jsonBody({ parent_id: newItem.parent_id || null, item_type: newItem.item_type, title: newItem.title, description: null, sort_order: Number(newItem.sort_order), estimated_minutes: Number(newItem.estimated_minutes), adjustment_reason: reason }) }); setNewItem({ title: "", item_type: "KNOWLEDGE_POINT", parent_id: "", estimated_minutes: "120", sort_order: "0" }); await refresh(); await client.invalidateQueries({ queryKey: ["plan-revisions", selected.id] }); } catch (caught) { setError(caught); } }
  async function changeStatus(item: PlanItem, status: PlanItemStatus) { const reason = window.prompt("请输入进度调整原因", "教师手动更新教学进度"); if (!reason) return; const notes = window.prompt("进度备注（可为空）", item.progress_notes ?? ""); if (notes === null) return; try { await api(`/teaching-plan-items/${item.id}`, { method: "PUT", ...jsonBody({ parent_id: item.parent_id, item_type: item.item_type, title: item.title, description: item.description, sort_order: item.sort_order, estimated_minutes: item.estimated_minutes, actual_minutes: item.actual_minutes, status, progress_notes: notes || null, version: item.version, adjustment_reason: reason }) }); await refresh(); await client.invalidateQueries({ queryKey: ["plan-revisions", selected?.id] }); } catch (caught) { setError(caught); } }

  return <>
    <PageHeader title="教学计划与进度" description="计划按学生学科隔离；每次结构或进度调整都保存不可变快照和原因。" />
    {error ? <ErrorNotice error={error} /> : null}
    <div className="mt-4 grid gap-6 xl:grid-cols-[250px_1fr_330px]">
      <section className="card h-fit"><h2 className="mb-3 font-semibold">长期计划</h2>{plans.data?.length ? <div className="space-y-2">{plans.data.map((row) => <button key={row.id} className={`w-full rounded-lg p-3 text-left text-sm ${selected?.id === row.id ? "bg-slate-900 text-white" : "bg-slate-50"}`} onClick={() => setSelectedId(row.id)}><strong className="block">{row.name}</strong><span className="opacity-70">{row.student_name} · {row.subject_name}</span></button>)}</div> : <p className="text-sm text-[var(--muted)]">暂无计划</p>}<form className="mt-5 space-y-3 border-t border-[var(--border)] pt-5" onSubmit={createPlan}><select className="field" value={newPlan.student_subject_id} onChange={(e) => setNewPlan({...newPlan,student_subject_id:e.target.value})} required><option value="">选择学生学科</option>{links.data?.map((row) => <option key={row.id} value={row.id}>{row.student_name} · {row.subject_name}</option>)}</select><input className="field" placeholder="计划名称" value={newPlan.name} onChange={(e) => setNewPlan({...newPlan,name:e.target.value})} required /><textarea className="field" placeholder="计划说明" value={newPlan.description} onChange={(e) => setNewPlan({...newPlan,description:e.target.value})} /><button className="button-primary w-full">创建计划</button></form></section>
      <section>{selected ? <div className="space-y-5"><article className="card"><p className="text-sm text-[var(--accent)]">{selected.student_name} · {selected.subject_name}</p><h2 className="mt-2 text-2xl font-semibold">{selected.name}</h2><p className="mt-2 text-sm text-[var(--muted)]">{selected.description || "暂无说明"}</p></article><article className="card"><h2 className="font-semibold">章节与知识点</h2>{selectedItems.length ? <div className="mt-4 space-y-3">{selectedItems.map((item) => <div key={item.id} className="rounded-xl border border-[var(--border)] p-4" style={{ marginLeft: item.parent_id ? 24 : 0 }}><div className="flex flex-wrap items-start justify-between gap-3"><div><span className="badge">{item.item_type === "CHAPTER" ? "章节" : item.item_type === "TOPIC" ? "主题" : "知识点"}</span><h3 className="mt-2 font-medium">{item.title}</h3><p className="mt-1 text-xs text-[var(--muted)]">预计 {item.estimated_minutes} 分钟 · 实际 {item.actual_minutes} 分钟</p></div><select className="field w-auto" aria-label={`${item.title}状态`} value={item.status} onChange={(e) => changeStatus(item, e.target.value as PlanItemStatus)}>{Object.entries(statusLabels).map(([value,label]) => <option key={value} value={value}>{label}</option>)}</select></div>{item.progress_notes ? <p className="mt-3 text-sm">{item.progress_notes}</p> : null}</div>)}</div> : <p className="mt-3 text-sm text-[var(--muted)]">尚无计划条目。</p>}<form className="mt-5 grid gap-3 border-t border-[var(--border)] pt-5 md:grid-cols-2" onSubmit={createItem}><input className="field" placeholder="条目标题" value={newItem.title} onChange={(e) => setNewItem({...newItem,title:e.target.value})} required /><select className="field" value={newItem.item_type} onChange={(e) => setNewItem({...newItem,item_type:e.target.value})}><option value="CHAPTER">章节</option><option value="KNOWLEDGE_POINT">知识点</option><option value="TOPIC">主题</option></select><select className="field" value={newItem.parent_id} onChange={(e) => setNewItem({...newItem,parent_id:e.target.value})}><option value="">无父条目</option>{selectedItems.map((item) => <option key={item.id} value={item.id}>{item.title}</option>)}</select><input className="field" type="number" min="0" placeholder="预计分钟" value={newItem.estimated_minutes} onChange={(e) => setNewItem({...newItem,estimated_minutes:e.target.value})} /><button className="button-primary md:col-span-2">新增条目</button></form></article></div> : <EmptyState>创建或选择一个教学计划。</EmptyState>}</section>
      <aside className="card h-fit"><h2 className="font-semibold">调整历史</h2>{revisions.data?.length ? <ol className="mt-4 space-y-3">{revisions.data.map((row) => <li className="border-l-2 border-slate-200 pl-3 text-sm" key={row.version_number}><strong>版本 {row.version_number}</strong><p className="mt-1 text-[var(--muted)]">{row.adjustment_reason}</p><time className="mt-1 block text-xs text-[var(--muted)]">{new Date(row.created_at).toLocaleString("zh-CN")}</time></li>)}</ol> : <p className="mt-3 text-sm text-[var(--muted)]">选择计划后显示历史。</p>}</aside>
    </div>
  </>;
}
